services:
  taskmanager-postgres:
    image: postgres:16.3
    environment:
      - 'POSTGRES_DB=bdotaskmanager'
      - 'POSTGRES_PASSWORD=bdo'
      - 'POSTGRES_USER=bdo'
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - "./conf.d:/etc/postgresql/conf.d:ro"
    networks:
      - taskmanager-network

  taskmanager-postgres-admin:
    depends_on:
      - taskmanager-postgres
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taskmanager.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 0
    volumes:
      - ../../.pgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:10000:80"
    networks:
      - taskmanager-network

  bdo-taskmanager-api:
    depends_on:
      - taskmanager-postgres
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskmanager-postgres/bdotaskmanager
      - SPRING_DATASOURCE_USERNAME=bdo
      - SPRING_DATASOURCE_PASSWORD=bdo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - taskmanager-network

    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://0.0.0.0:80/misc/ping"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  taskmanager-network:
    external: true
